name: Continuous Integration
on:
  - push

jobs:
  Continuous-Integration:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install
